[package]
name = "spectrust"
version = "0.1.0"
edition = "2021"

[dependencies]
rustfft = "6.4"
num-complex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "stft_test"
path = "src/bin/stft_test.rs"

[[bin]]
name = "comprehensive_test"
path = "src/bin/comprehensive_test.rs"

[[bin]]
name = "simple_debug"
path = "src/bin/simple_debug.rs"

[[bin]]
name = "shared_data_test"
path = "src/bin/shared_data_test.rs"
