version: '3.8'

services:
  rust-stft:
    build:
      context: .
      dockerfile: rust.Dockerfile
    volumes:
      - ./comparison_results:/workspace/comparison_results
    container_name: spectrust-rust

  python-stft:
    build:
      context: .
            dockerfile: docker/py.Dockerfile
    volumes:
      - ./comparison_results:/workspace/comparison_results
      - ./standalone_stft.py:/workspace/standalone_stft.py
      - ./run_full_comparison.py:/workspace/run_full_comparison.py
    depends_on:
      - rust-stft
    container_name: spectrust-python
